name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    container: node:alpine
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Setup PostgreSQL
        run: node backend/tests/ci-setup.cjs
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

      - name: Run Tests
        run: pnpm run test
        env:
          CORS_ORIGIN: http://localhost:3000
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
          JWT_SECRET: test
